### ISSUE TITLE
Provide dependencies based on aem-sdk-api 2021.2.4944.20210221T230729Z-210128 for Java 8 compatibility

### ISSUE THREAD

**Issue by kwin** [wcm-io/wcm-io-tooling-aem-cloud-dependencies#2]
All versions newer than `2020.11.4506.20201112T235200Z-201028.0000` and older than `2021.2.4944.20210221T230729Z-210128` contain Java 11 classes (e.g. `com.day.cq.wcm.foundation.AdaptiveImageHelper`). This leads to issues when using plugins like https://www.mojohaus.org/animal-sniffer/animal-sniffer-maven-plugin/ which does not yet support Java 11 sources (https://github.com/mojohaus/animal-sniffer/pull/91).
It would be great to have a new release for 2021.2.4944.20210221T230729Z-210128 which would be fully usable with Java 8 build plugins again...

**Comment by stefanseifert** [comment]
should be fixed with the last 3 releases? - latest yesterday

**Comment by kwin** [comment]
Indeed, sorry you are too fast for me: https://github.com/wcm-io/wcm-io-tooling-aem-cloud-dependencies/releases/tag/2021.2.4944.20210221T230729Z-210128.0000.
